name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t mi-app .

      - name: Simular deployment
        run: echo "🚀 Deploy realizado correctamente"